version: "3.9"

services:
    db:
        image: postgres:15
        container_name: superliga-db
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: oleg
            POSTGRES_PASSWORD: oleg
            POSTGRES_DB: betting
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
